import type { Metadata } from "next";
import "./globals.scss";
import Header from "@/components/Header";
import {Montserrat} from "next/font/google"
export const metadata: Metadata = {
  title: "  App",
  description: "Generated by create next app",
};
const montserrat = Montserrat({
  subsets:["latin"], 
  weight: ['400', '500','600','700','800'],
  style: ['normal', 'italic'],})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
